Repository googleapis/python-compute, pull requests merged in 2021-08, with the labels that each got.

#75 feat: adding samples to start/stop/reset operations
  samples/snippets/sample_start_stop.py
  samples/snippets/test_sample_default_values.py
  samples/snippets/test_sample_start_stop.py
Labels: api: compute, cla: yes, kokoro:run, samples

#96 ci: require samples checks
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, samples, api: compute

#98 chore: fix INSTALL_LIBRARY_FROM_SOURCE in noxfile.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: cla: yes, api: compute, context: none

#99 chore(samples): fix LRO wrapper
  samples/snippets/quickstart.py
  samples/snippets/sample_default_values.py
  samples/snippets/sample_start_stop.py
  samples/snippets/test_sample_start_stop.py
Labels: cla: yes, samples, api: compute

#106 chore: remove 2.7 from samples noxfile
  noxfile.py
  samples/snippets/noxfile.py
  scripts/readme-gen/templates/install_deps.tmpl.rst
  synth.metadata
Labels: cla: yes, api: compute, context: none

#102 fix: correct region tag formatting
  samples/snippets/sample_pagination.py
Labels: automerge, cla: yes, api: compute

#108 fix: Updated max_results to 100 to avoid too many API calls
  samples/snippets/sample_pagination.py
Labels: cla: yes, samples, api: compute

#105 tests: add cases for int64 field, map pagination, field that start with capital letter
  tests/system/test_instance_group.py
  tests/system/test_pagination.py
  tests/system/test_smoke.py
Labels: cla: yes, api: compute

#113 chore: disable dependency dashboard
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, api: compute, context: none
