Repository googleapis/python-compute, pull requests merged in 2021-09, with the labels that each got.

#118 chore: reference main branch of google-cloud-python
  README.rst
Labels: cla: yes, api: compute

#121 chore: blacken samples noxfile template
  samples/snippets/noxfile.py
  synth.metadata
Labels: cla: yes, api: compute, context: none

#117 feat: Adding firewall samples.
  samples/snippets/sample_firewall.py
  samples/snippets/test_sample_firewall.py
Labels: cla: yes, samples, api: compute

#116 chore: add codeowner_team to repo-metadata.json
  .repo-metadata.json
Labels: cla: yes, api: compute
