Repository googleapis/python-compute, pull requests merged in 2021-07, with the labels that each got.

#69 docs: samples docstring and comments update
  samples/snippets/quickstart.py
Labels: api: compute, cla: yes, samples

#74 chore: add actools team as codeowner
  .github/CODEOWNERS
Labels: api: compute, cla: yes

#81 fix(deps): pin 'google-{api,cloud}-core', 'google-auth' to allow 2.x versions
  setup.py
Labels: api: compute, automerge, cla: yes

#67 chore: update templated files
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/samples/python3.9/common.cfg
  .kokoro/samples/python3.9/continuous.cfg
  .kokoro/samples/python3.9/periodic-head.cfg
  .kokoro/samples/python3.9/periodic.cfg
  .kokoro/samples/python3.9/presubmit.cfg
  .kokoro/test-samples-impl.sh
  .pre-commit-config.yaml
  CONTRIBUTING.rst
  docs/conf.py
  samples/snippets/noxfile.py
  synth.metadata
Labels: api: compute, cla: yes, context: none

#83 fix: Kokoro uses separate project for concurent tests.
  samples/snippets/noxfile_config.py
Labels: api: compute, automerge, cla: yes

#85 chore: fix kokoro config for samples
  .kokoro/samples/python3.6/periodic-head.cfg
  .kokoro/samples/python3.7/periodic-head.cfg
  .kokoro/samples/python3.8/periodic-head.cfg
  .kokoro/samples/python3.9/periodic-head.cfg
  synth.metadata
Labels: api: compute, automerge, cla: yes, context: none
