Repository googleapis/python-compute, pull requests merged in 2022-06, with the labels that each got.

#288 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: api: compute, size: xs

#292 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: automerge, api: compute, size: s

#297 chore(docs): Fix a minor typo
  samples/ingredients/instances/resume.py
  samples/ingredients/instances/suspend.py
  samples/snippets/instances/resume.py
  samples/snippets/instances/suspend.py
Labels: api: compute, size: s
